default: &DEFAULT
  epochs_number: 100
  batch_size: 64

MLP:
  <<: *DEFAULT
  data_dir: "Data"
  checkpoint_dir: "checkpoints/mlp"
  log_dir: "logs/mlp"
  dataset_class: "AudioDataset"
  learning_rate: 0.0001

CNN:
  <<: *DEFAULT
  data_dir: "Data"
  checkpoint_dir: "checkpoints/cnn"
  log_dir: "logs/cnn"
  dataset_class: "AudioDataset"
  learning_rate: 0.0001
