default: &DEFAULT
  #files and directories names
  datasets_dir: "Datasets"
  storage_dir: "Storage"
  features_dir: "features"
  models_dir: "models"
  logs_dir: "logs"
  train_data_dir: "FSDKaggle2018.audio_train"
  test_data_dir: "FSDKaggle2018.audio_test"
  metadata_dir: "FSDKaggle2018.meta"
  train_meta_file: "train_post_competition.csv"
  test_meta_file: "test_post_competition_scoring_clips.csv"
  labels_file: "labels.json"
  validation_dir: "validation"
  validation_meta_file: "validation.csv"
  #classes number
  classes_number: 41

log_mel:
  <<: *DEFAULT
  #parameters for extracting log-mel features
  features_type: "log_mel"
  sample_rate: 32000
  fft_window_size: 2048
  mels_number: 64
  hop_length: 1024
  min_frequency: 50.0
  # use max_frequency as None
  max_frequency:

VGGish:
  #<<: *DEFAULT
  model_name: "VGGish"
  #model parameters
  conv_blocks_number: 5
  kernel_size_1st_dim: 3
  kernel_size_2nd_dim: 3
  stride_1st_dim: 1
  stride_2nd_dim: 1
  padding_1st_dim: 1
  padding_2nd_dim: 1
  add_bias_to_blocks: False
  init_layers_manually: False  #was True
  std_scale_factor: 3.0
  max_pool_kernel_size_1st_dim: 2
  max_pool_kernel_size_2nd_dim: 2
  max_pool_stride_1st_dim: 2
  max_pool_stride_2nd_dim: 2
  add_bias_to_fc: True
  #optimiser parameters
  learning_rate: 0.001
  beta_1: 0.9
  beta_2: 0.999
  eps: 1e-08
  weight_decay: 0.0
  amsgrad: False
  learning_rate_decay: 0.9
  learning_rate_decay_step: 100
  #data generation parameters
  batch_size: 128
  folds_number: 4
  holdout_fold: 1
  seed: 2020
  input_frames_number: 128
  epochs_limit: 15  # was 10
  eval_audios_number: 1500  # was 1000
